name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Test
      run: make test
